const coachesData = [
    {
        name: "John Wyllie",
        title: "Director of Coaching (DOC)",
        slug: "john-wyllie",
        photo: "/images/coaches/placeholder.jpg",
        hometown: "Glasgow, Scotland",
        favoriteTeam: "Rangers FC",
        favoriteMeal: "Steak Pie",
        license: "National C License",
        yearsExperience: null,
        reason: "To build a club that focuses on long-term player development and creates a positive, competitive environment for the community.",
        philosophy: "Develop intelligent players who understand the game, are technically proficient, and play with passion and creativity.",
        email: "doc@cusc.soccer",
        hidden: false,
        teams: ["2011 Girls Red", "2016 Boys Red"],
        isDefault: true
    },
    {
        name: "Phil Hulme",
        title: "Technical Coordinator (11v11)",
        slug: "phil-hulme",
        photo: "/images/coaches/phil-hulme.jpg",
        hometown: "Manchester, UK",
        favoriteTeam: "Manchester United",
        favoriteMeal: "Lamb Vindaloo",
        license: "UEFA B License & USSF D License",
        yearsExperience: "15+",
        reason: "To help my kids integrate into the local soccer community and find their tribe.",
        philosophy: "I believe winning is a byproduct of skill and technique and it is my responsibility to provide the best environment for the individual technical development of each player.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Michelle McHone",
        title: "Recreational Coordinator",
        slug: "michelle-mchone",
        photo: "/images/coaches/placeholder.jpg",
        hometown: "Portland, OR",
        favoriteTeam: "Portland Thorns",
        favoriteMeal: "Tacos",
        license: "National C License",
        yearsExperience: null,
        reason: "To ensure every child has a fun and safe place to fall in love with soccer, regardless of their skill level.",
        philosophy: "Soccer should be fun! My goal is to foster a love for the game through positive reinforcement, teamwork, and skill-building activities.",
        email: "rec@cusc.soccer",
        hidden: false,
        teams: ["N/A"],
        isDefault: false
    },
    {
        name: "Thomas Knight",
        title: "Coach",
        slug: "thomas-knight",
        photo: "/images/coaches/thomas-knight.jpg",
        hometown: "Stockton-On-Tees, England",
        favoriteTeam: "Middlesbrough FC",
        favoriteMeal: "Italian",
        license: "USSF D License",
        yearsExperience: "15+",
        reason: "I chose to join CUSC as the club's philosophy suits my coaching vision.",
        philosophy: "I work with players on their fundamentals driven through a fun, challenging, and rewarding environment.",
        //email: "rec@cusc.soccer",
        hidden: false,
        teams: ["U13 Boys Red"],
        isDefault: false
    },
    {
        name: "Mohammed Ibrahim Ahmad",
        title: "Coach",
        slug: "mohammed-ibrahim-ahmad",
        photo: "/images/coaches/mohammed-ibrahim-ahmad.jpg",
        hometown: "London",
        favoriteTeam: "Manchester United",
        favoriteMeal: "Steak and fries",
        license: "Grassroots (11v11 in Person, 9v9 In Person, 7v7 In Person, 4v4 In Person, Intro)",
        yearsExperience: "7",
        reason: "I joined CUSC because I was impressed by its focus on player development and community. I wanted the opportunity to help players reach their potential in a supportive environment while contributing to a club that shares my passion for soccer and long-term growth.",
        philosophy: "I believe in developing the whole player, not just winning games. I focus on teaching sound technical skills, encouraging intelligent decision-making, and creating a positive, inclusive environment where players work hard, enjoy the game, and grow in confidence. If players leave each session better than they arrived, I've done my job as a coach.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Kelli Anderson",
        title: "Coach",
        slug: "kelli-anderson",
        photo: "/images/coaches/kelli-anderson.jpg",
        hometown: "Missoula, Montana",
        favoriteTeam: "Portland Thorns",
        favoriteMeal: "Homemade Calzones",
        license: "Grassroots (9v9 In Person, 11v11 in Person)",
        yearsExperience: "15+",
        reason: "I live in the Clackamas area and wanted to get involved with a club team close to the community in which I live.",
        philosophy: "I want to develop resilient, technically proficient and intelligent soccer players who value teamwork, creativity and sportsmanship.\nI like a possession style game where we build up from the back, maintain composure, and press quickly when the ball is lost.\nOff the field I want to foster a safe environment where players have the confidence to take risks, learn from their mistakes and grow as an athlete and person.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Andrey Baranovich",
        title: "Coach",
        slug: "andrey-baranovich",
        photo: "/images/coaches/andrey-baranovich.jpg",
        hometown: "Oregon City",
        favoriteTeam: "Timbers",
        favoriteMeal: "Thai",
        license: "Grassroots (Intro)",
        yearsExperience: "2",
        reason: "Great staff and program.",
        philosophy: "Do my best to develop and teach soccer.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Grace Barrett",
        title: "Coach",
        slug: "grace-barrett",
        photo: "/images/coaches/grace-barrett.jpg",
        hometown: "Clackamas",
        favoriteTeam: "Portland Thorns",
        favoriteMeal: "A good bowl of pasta",
        license: "USSF D License",
        yearsExperience: "4",
        reason: "I wanted to get back to the game and what better way than being involved in the club I grew up playing at",
        philosophy: "I believe in development first, not only as a player but also as a person. I feel like a player cannot be at their best unless they are supported mentally and physically.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Carlos Betancourt",
        title: "Coach",
        slug: "carlos-betancourt",
        photo: "/images/coaches/carlos-betancourt.jpg",
        hometown: "Milwaukie",
        favoriteTeam: "Club America",
        favoriteMeal: "Mexican",
        license: "Grassroots (9v9 In Person, 11v11 in Person, Intro)",
        yearsExperience: "1",
        reason: "To help develop players",
        philosophy: "Train hard to be successful",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Kathleen Betancourt",
        title: "Coach",
        slug: "kathleen-betancourt",
        photo: "/images/coaches/kathleen-betancourt.jpg",
        hometown: "Milwaukie",
        favoriteTeam: "Club America",
        favoriteMeal: "Italian",
        license: "USSF D License",
        yearsExperience: "15+",
        reason: "I like the style of play provided by the club and the family atmosphere.",
        philosophy: "I am a developer; I like to help players reach their potential through hard work. It doesn't matter where you start as long as you have to drive to work through all obstacles to get where you want to be.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Wade Bird",
        title: "Coach",
        slug: "wade-bird",
        photo: "/images/coaches/wade-bird.jpg",
        hometown: "Clackamas",
        favoriteTeam: "Liverpool",
        favoriteMeal: "Seafood",
        license: "Grassroots (7v7 Online, 4v4 Online, Intro, 9v9 Online, 11v11 Online)",
        yearsExperience: "10",
        reason: "To teach kids the game that I enjoy and watch them grow!",
        philosophy: "Development at all costs. Especially at the youth level.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Jake Borrer",
        title: "Coach",
        slug: "jake-borrer",
        photo: "/images/coaches/jake-borrer.jpg",
        hometown: "Liverpool",
        favoriteTeam: "Liverpool Football Club",
        favoriteMeal: "Curry",
        license: "English FA Level 2 in Football Coaching",
        yearsExperience: "10",
        reason: "I chose to join CUSC as their values and beliefs around long term player development and reputation as a community first club align with my own values as a person and as a coach.",
        philosophy: "I believe in holistic player development. I want to develop players that have high levels of technical skill and tactical understanding, whilst also growing into people with important psychosocial traits such as resiliance, problem solving and leadership.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Brandon Borschel",
        title: "Coach",
        slug: "brandon-borschel",
        photo: "/images/coaches/brandon-borschel.jpg",
        hometown: "East Brunswick, New Jersey",
        favoriteTeam: "NY Cosmos",
        favoriteMeal: "Filet Mignon",
        license: "USSF D License",
        yearsExperience: "9",
        reason: "To have a positive impact on young athletes and be more involved in the sport I love and grew up playing.",
        philosophy: "To help foster a positive environment for all players, where they build confidence in themselves and find joy in the game and in playing with their teammates.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Josh Cameron",
        title: "Coach",
        slug: "josh-cameron",
        photo: "/images/coaches/josh-cameron.jpg",
        hometown: "Gresham, OR",
        favoriteTeam: "Portland Timbers",
        favoriteMeal: "I love Mexican food!",
        license: "Grassroots (11v11 Online)",
        yearsExperience: "15+",
        reason: "For the opportunity to coach for a well-established club, with talented players and coaches.",
        philosophy: "I believe coaching is more than just teaching the game. It's an opportunity to show and teach players life lessons. From a soccer standpoint, I put a heavy emphasis on the technical side of the game. The little things matter!",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Matt Crouch",
        title: "Coach",
        slug: "matt-crouch",
        photo: "/images/coaches/matt-crouch.jpg",
        hometown: "Columbia, Missouri, USA",
        favoriteTeam: "Newcastle United",
        favoriteMeal: "Tacos",
        license: "Grassroots (11v11 Online)",
        yearsExperience: "14",
        reason: "I am also a parent of a CUSC player.",
        philosophy: "The Core Mission: To develop skilled, intelligent soccer players who understand the value of hard work and teamwork, while fostering a deep, lifelong passion for the sport.\nI believe in building thinking, technically sound soccer players. I believe training should focus heavily on:\nPersonal Skills: Mastering ball control, technical execution, and confidence in 1v1 situations.\nSpatial Awareness and Timing: Teaching players how to read the game, understand when to exploit space, and master the timing of passes, runs, and defensive movements.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Sean Cusack",
        title: "Coach",
        slug: "sean-cusack",
        photo: "/images/coaches/sean-cusack.jpg",
        hometown: "Eugene",
        favoriteTeam: "Manchester United",
        favoriteMeal: "Tacos",
        license: "Grassroots (7v7 Online, 9v9 Online)",
        yearsExperience: "5",
        reason: "My son was playing and I wanted to be a part of his sports development.",
        philosophy: "Have fun, give it your best, and stay positive no matter what.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Brian Dundon",
        title: "Coach",
        slug: "brian-dundon",
        photo: "/images/coaches/brian-dundon.jpg",
        hometown: "Happy Valley",
        favoriteTeam: "PSG",
        favoriteMeal: "Chips and Salsa",
        license: "Grassroots (7v7 Online, Intro, 9v9 Online)",
        yearsExperience: "15",
        reason: "Player development, mentorship",
        philosophy: "Build a strong foundation of skills. Reinforce the correct style of play for development, challenge by teaching and pushing for excellence. Get the kids to buy into hard work, results will come but the goal is to have fun!",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Andre Frelke",
        title: "Coach",
        slug: "andre-frelke",
        photo: "/images/coaches/andre-frelke.jpg",
        hometown: "Wuerzburg",
        favoriteTeam: "Bayern Munich",
        favoriteMeal: "Rolladen",
        license: "Grassroots (9v9 In Person, 11v11 in Person, Intro, 4v4 Online)",
        yearsExperience: "4",
        reason: "My kids play for CUSC",
        philosophy: "Player centric learning with a focus on teamwork and growth",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Kevin Gelbrich",
        title: "Coach",
        slug: "kevin-gelbrich",
        photo: "/images/coaches/kevin-gelbrich.jpg",
        hometown: "Eugene, Oregon",
        favoriteTeam: "Portland Thorns",
        favoriteMeal: "Dungeness Crab",
        license: "USSF C License",
        yearsExperience: "9",
        reason: "Both of my daughters play in the club and I started as a coach for Rec back when my oldest was in kindergarten and she is now going to be a Sophomore at Nelson",
        philosophy: "Ensure a fun, challenging environment that supports the continued growth and development of our players.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Jeff Gillin",
        title: "Coach",
        slug: "jeff-gillin",
        photo: "/images/coaches/jeff-gillin.jpg",
        hometown: "Philadelphia",
        favoriteTeam: "Portland Timbers",
        favoriteMeal: "Pizza",
        license: "Grassroots (Intro)",
        yearsExperience: "5",
        reason: "To help mentor kids and coach and help my son in the club",
        philosophy: "The three most controllable things as a player are effort, courage, and communication",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Josh Reece Green",
        title: "Coach",
        slug: "josh-reece-green",
        photo: "/images/coaches/josh-reece-green.jpg",
        hometown: "Middlesbrough",
        favoriteTeam: "Middlesbrough",
        favoriteMeal: "Chicken Parmesan",
        license: "Grassroots (Intro)",
        yearsExperience: "5",
        reason: "I have a great appreciation for the culture and organisation for the club. I feel as though I have a great deal to offer and my coaching style and personality will be a great fit for the club.",
        philosophy: "My coaching philosophy is empowering players to take control of their learning with ownership and responsibility, whilst presenting a positive and friendly working environment. I also believe in a holistic coaching approach with a focus of developing players as a whole, developing technical fundamentals, game understanding and confidence.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Shaun Hachquet",
        title: "Coach",
        slug: "shaun-hachquet",
        photo: "/images/coaches/shaun-hachquet.jpg",
        hometown: "Oregon City, OR",
        favoriteTeam: "Timbers",
        favoriteMeal: "Steak",
        license: "Grassroots (11v11 in Person, 11v11 Online, 4v4 Online, 9v9 Online, 9v9 In Person, Intro)",
        yearsExperience: "3",
        reason: "I had the opportunity to start as an assistant when my oldest started playing. I found the clubs leadership has created a collaborative environment to learn from and share knowledge with a common purpose.",
        philosophy: "To be player development focused, where learning and improvement matter more than game results. I encourage strong teamwork and teaching kids to support one another and understand the game beyond individual skills. Practices are designed to be fun, energetic, and engaging so players stay motivated and excited to return. Ultimately, the goal is to create an environment where every player feels valued, challenged, and inspired to grow.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Angela Hillebrand",
        title: "Coach",
        slug: "angela-hillebrand",
        photo: "/images/coaches/angela-hillebrand.jpg",
        hometown: "Happy Valley Oregon",
        favoriteTeam: "Portland Timbers!",
        favoriteMeal: "Grilled veggies and Steak",
        license: "Grassroots (Intro, 7v7 Online)",
        yearsExperience: "5",
        reason: "I originally started coaching recreational soccer for my kid's teams, and quickly learned how much I enjoyed it!\nWithout encouragement from CUSC, I decided to continue developing as a coaching and take the next step into the developmental program. I'm excited to be Assistant Coaching this year, continuing to learn, and helping our players grow their skills and love of the game.",
        philosophy: "My goal is to create a positive, supportive environment where players feel encouraged to learn, take risks, and grow. I want kids to develop their soccer skills while also building confidence, learning to be great teammates, and developing a genuine love of the game. I also value creating a connected team community where players, coaches and families feel welcome and supported.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Everett Mayers Jr",
        title: "Coach",
        slug: "everett-mayers-jr",
        photo: "/images/coaches/everett-mayers-jr.jpg",
        hometown: "Milwaukie",
        favoriteTeam: "Bayern München",
        favoriteMeal: "Steak and potatoes",
        license: "Grassroots (Intro, 9v9 In Person, 11v11 in Person)",
        yearsExperience: "12",
        reason: "I chose to join CUSC as a coach because I am passionate about helping young athletes develop both on and off the field. I believe sports provide valuable opportunities to build confidence, discipline, teamwork, and leadership skills that extend far beyond the game itself.\n\nHaving been involved in youth athletics, I wanted to contribute to an organization that is committed to player development and creating a positive environment for athletes to grow. CUSC’s focus on fostering skill development, sportsmanship, and a strong sense of community aligns with my own values as a coach.\n\nI am excited about the opportunity to support players in reaching their potential, help them achieve their goals, and be a positive influence in their athletic journey.",
        philosophy: "My coaching philosophy is centered on player development, teamwork, and creating a positive learning environment. I believe that success is measured not only by wins and losses, but by the growth of each player as an athlete and as an individual.\n\nI strive to develop technically skilled, tactically aware, and confident players who understand the value of hard work, discipline, accountability, and sportsmanship. My goal is to create an environment where players feel challenged, supported, and motivated to continuously improve.\n\nI also believe in fostering a team-first culture built on respect, communication, and trust. By emphasizing effort, character, and a strong work ethic, I aim to help players develop skills and values that will benefit them both on the field and in their everyday lives.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Jon Kizzar",
        title: "Coach",
        slug: "jon-kizzar",
        photo: "/images/coaches/jon-kizzar.jpg",
        hometown: "Clackamas Oregon",
        favoriteTeam: "Manchester City",
        favoriteMeal: "Burrito",
        license: "Grassroots (11v11 Online)",
        yearsExperience: "6",
        reason: "My daughter joined CUSC.",
        philosophy: "Player Improvement",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Ruben Martin Macias",
        title: "Coach",
        slug: "ruben-martin-macias",
        photo: "/images/coaches/ruben-martin-macias.jpg",
        hometown: "Las Palmas de GC, Spain",
        favoriteTeam: "UD Las Palmas",
        favoriteMeal: "Spaghetti with Meatballs",
        license: "USSF C License",
        yearsExperience: "4",
        reason: "I joined because they gave me the opportunity to grow in my coaching development and get the experience to develop players the love for this beautiful sport",
        philosophy: "I want the ball all the time and get everyone to have fun by displaying their strengths on the field while helping each other cover for those weaknesses. Keeping the ball and passing among the teammates is something crucial for the team to thrive and being able to score goals through passing and everyone's collaboration. We are a team and nobody is above the team.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Kevin McAllister",
        title: "Coach",
        slug: "kevin-mcallister",
        photo: "/images/coaches/kevin-mcallister.jpg",
        hometown: "Tigard, OR",
        favoriteTeam: "Leicester City",
        favoriteMeal: "Food",
        license: "USSF D License",
        yearsExperience: "8",
        reason: "I enjoy coaching for the club.",
        philosophy: "Build great players to make better people.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Jane Mendoza",
        title: "Coach",
        slug: "jane-mendoza",
        photo: "/images/coaches/jane-mendoza.jpg",
        hometown: "London, England before moving to Clackamas.",
        favoriteTeam: "Crystal Palace FC",
        favoriteMeal: "Tacos",
        license: "USSF D License",
        yearsExperience: "7",
        reason: "I love the sense of community here at Clackamas United.",
        philosophy: "My goal is to instill a lasting love for soccer, a robust technical and tactical understanding of the game, and the confidence to keep failing until you succeed. I am particularly focused on showing girls that they are tough, capable, and creative problem solvers. Statistically, more than 50% of girls will drop out of organized sports before the age of 14, usually due to social pressures and poor self esteem and confidence. Many of these girls will grow up to report that they feel they missed out on the social connections, and personal growth, but feel they are too old to return to sport. I want to be a part of changing these statistics.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Joel Munoz",
        title: "Coach",
        slug: "joel-munoz",
        photo: "/images/coaches/joel-munoz.jpg",
        hometown: "Portland",
        favoriteTeam: "FC Barcelona",
        favoriteMeal: "Brisket",
        license: "Grassroots (Intro, 4v4 Online, 11v11 Online)",
        yearsExperience: "11",
        reason: "To help my kids teams improve.",
        philosophy: "To help the players be the best version of themselves that they can be. While hopefully having a good time in the process.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Sarah Owens",
        title: "Coach",
        slug: "sarah-owens",
        photo: "/images/coaches/sarah-owens.jpg",
        hometown: "Gardnerville, Nevada",
        favoriteTeam: "Portland Thorns",
        favoriteMeal: "Street tacos and an ice cold bottled Coke",
        license: "Grassroots (Intro)",
        yearsExperience: "2",
        reason: "I have also had a love for soccer, playing throughout my childhood into high school, so when my son decided he wanted to play soccer, I wanted to be along side him and watch his love for soccer grow. It’s been an amazing experience and something I truly enjoy doing.",
        philosophy: "As a coach, I want to help my players develop a passion for the game by providing them with the tools they need to play the game successfully, in a safe, respectful, and positive environment.\n\nSoccer should be played with creativity, intelligence, and control. The goal is to become comfortable when in possession of the ball and trusting their skills. The goal is to guide each player in learning and reading the field, understanding their role and position. The goal is to build teamwork and communication to become a cohesive unit, trusting one another.\n\nIt is not about the scoreboard. It is about each player learning, understanding, and valuing respect, resilience, empathy, teamwork, and sportsmanship, on and off the pitch.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Joel Palioca",
        title: "Coach",
        slug: "joel-palioca",
        photo: "/images/coaches/joel-palioca.jpg",
        hometown: "Happy Valley",
        favoriteTeam: "Chelsea",
        favoriteMeal: "Flying Pie Pizza",
        license: "USSF D License",
        yearsExperience: "5",
        reason: "To help support my kids, and the other coaches and kids surrounding them.",
        philosophy: "I prioritize developing people first, athletes second.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Tyson Quibell",
        title: "Coach",
        slug: "tyson-quibell",
        photo: "/images/coaches/tyson-quibell.jpg",
        hometown: "Emo, Ontario, Canada",
        favoriteTeam: "Liverpool",
        favoriteMeal: "Piccanha",
        license: "Grassroots (Intro)",
        yearsExperience: "7",
        reason: "I chose CUSC because of its focus on development. From our style of play to how we run practices, development, especially for our younger players, deveopment is the goal. I'm proud to be a part of that as a coach.",
        philosophy: "My philosophy for this age group is to use a possession-based style of play to maximize player development. I encourage our teams to build out from the back, which gives players maximum touches and forces them to develop the individual skills needed to keep the ball under pressure. We play with a high-energy, high-pressure approach to keep the game fast-paced and exciting. My ultimate goal is to foster a fun, competitive environment where third graders fall in love with the ball, learn to play with pace, and develop the technical foundation for the next level.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Brian Rants",
        title: "Coach",
        slug: "brian-rants",
        photo: "/images/coaches/brian-rants.jpg",
        hometown: "Canby Oregon",
        favoriteTeam: "Everton FC",
        favoriteMeal: "Pad Thai",
        license: "I have started Grassroots training",
        yearsExperience: "1",
        reason: "Soccer brings joy to my life, and CUSC has helped my son develop as an athlete, a leader, and a friend.",
        philosophy: "POF: Put others first. Play without fear. Praise others’ feats.\n\nIf you make a mistake, own it.\nIf you have success, share it.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Victor Renderos",
        title: "Coach",
        slug: "victor-renderos",
        photo: "/images/coaches/victor-renderos.jpg",
        hometown: "Beaverton Oregon",
        favoriteTeam: "FC Barcelona",
        favoriteMeal: "Ice Cream",
        license: "USSF D License",
        yearsExperience: "3",
        reason: "To help and prepare kids for whats ahead of them.",
        philosophy: "Development is top priority. everything else comes afterwards",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Pedro Reyes",
        title: "Coach",
        slug: "pedro-reyes",
        photo: "/images/coaches/pedro-reyes.jpg",
        hometown: "Klamath Falls",
        favoriteTeam: "Mexico",
        favoriteMeal: "Mole",
        license: "Grassroots (Intro)",
        yearsExperience: "7",
        reason: "To coach my kids",
        philosophy: "Have fun, learn new skills",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Joe Salvati",
        title: "Coach",
        slug: "joe-salvati",
        photo: "/images/coaches/joe-salvati.jpg",
        hometown: "Klamath Falls, OR",
        favoriteTeam: "Portland Timbers & Liverpool",
        favoriteMeal: "Tacos!",
        license: "Grassroots (Intro)",
        yearsExperience: "6",
        reason: "After my son outgrew the local recreational league, we decided to explore what CUSC had to offer. When he became eligible for a classic team, I was lucky enough to step in as an assistant coach, and it has been a rewarding experience ever since. Both as a parent and a coach, I truly value the principles of CUSC and the environment it provides for my son and me to develop our passion for the game.",
        philosophy: "I strive to maintain a balance between a developmental philosophy and technical instruction. It is important to me to convey the reasoning behind what we're doing so the players can internalize those concepts and exercise their own judgment on the field, rather than just following orders. Ultimately, however, the priority is having fun. If we are not having fun playing soccer, then we're doing something wrong.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Adis Sehovic",
        title: "Coach",
        slug: "adis-sehovic",
        photo: "/images/coaches/adis-sehovic.jpg",
        hometown: "Sarajevo, Bosnia and Herzegovina",
        favoriteTeam: "Real Madrid",
        favoriteMeal: "Pizza",
        license: "Grassroots (Intro)",
        yearsExperience: "2",
        reason: "Both of my sons play for the club. We are very happy with their progress and want to contribute by sharing knowledge with young athletes.",
        philosophy: "Practice makes it perfect. It's the effort that counts the most. It's important that we improve as individuals each day and to learn how to respect others.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Joel Shungu",
        title: "Coach",
        slug: "joel-shungu",
        photo: "/images/coaches/joel-shungu.jpg",
        hometown: "Paris, France",
        favoriteTeam: "Paris Saint-Germain",
        favoriteMeal: "Shrimp pasta",
        license: "USSF D License",
        yearsExperience: "6",
        reason: "I chose to join Clackamas United Soccer Club because of its strong commitment to player development and the incredible community that surrounds the club. From the moment I became involved, it was clear that CUSC is about more than just soccer, it is a place where players, families, coaches, and staff genuinely support one another and work together to create a positive environment for young athletes.\n\nAs a coach, I wanted to be part of a club that values both development and relationships. I enjoy helping players grow in their confidence, character, and love for the game, and I believe the community at CUSC makes that possible. The club provides a place where players can be challenged, supported, and encouraged to become the best version of themselves both on and off the field. Being part of that mission is what drew me to CUSC and continues to make coaching here so rewarding.",
        philosophy: "My coaching philosophy is centered on developing the whole player, not just the soccer player. I believe the game is a powerful tool to teach discipline, accountability, resilience, teamwork, and confidence. My goal is to create an environment where players are challenged, supported, and encouraged to grow every day.\n\nOn the field, I want my teams to play with courage, intensity, and purpose. I emphasize technical development, decision-making, and understanding the game rather than simply focusing on results. Winning is important, but development is the priority because long-term growth ultimately leads to success.\n\nI also believe relationships matter. Players perform their best when they know their coach cares about them as people first. I strive to build trust with my players and families while creating a culture where effort, attitude, and commitment are valued. My goal is for every player to leave my program not only as a better soccer player, but as a better teammate, leader, and person.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Livia Silva",
        title: "Coach",
        slug: "livia-silva",
        photo: "/images/coaches/livia-silva.jpg",
        hometown: "Rio de Janeiro",
        favoriteTeam: "Fluminense",
        favoriteMeal: "Rice and Beans (Brasil)",
        license: "Grassroots (Intro, 4v4 Online, 11v11 in Person)",
        yearsExperience: "3",
        reason: "I joined CUSC because I wanted to be part of a club that genuinely cares about developing players both on and off the field. From the moment I learned about the club, I appreciated its focus on creating a positive environment where players can improve, gain confidence, and enjoy the game. As a coach, I am passionate about helping young athletes grow, and CUSC provided the perfect opportunity to do that while also continuing my own development within a supportive coaching community.",
        philosophy: "My coaching philosophy is centered on player development, enjoyment of the game, and creating a positive learning environment. I believe soccer should challenge players to grow both as athletes and as individuals. My goal is to help players develop strong technical skills, tactical understanding, confidence, and character while fostering a genuine love for the game.\n\nI strive to create an environment where players feel supported, encouraged to take risks, and motivated to learn from both successes and mistakes. I value hard work, teamwork, respect, and accountability, and I believe these qualities are just as important as winning. While competition is an important part of sports, my primary focus is on helping each player reach their full potential and preparing them for long-term success both on and off the field.\n\nAs a coach, I am committed to continuous learning and adapting my methods to meet the needs of my players, ensuring that every athlete has the opportunity to develop, contribute, and enjoy their soccer journey.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Sean Snodgrass",
        title: "Coach",
        slug: "sean-snodgrass",
        photo: "/images/coaches/sean-snodgrass.jpg",
        hometown: "Clackamas, OR",
        favoriteTeam: "My daughters",
        favoriteMeal: "Pasta",
        license: "Grassroots (Intro)",
        yearsExperience: "4",
        reason: "For my daughters",
        philosophy: "Have fun and learn to be good team mates",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Jess Strickland",
        title: "Coach",
        slug: "jess-strickland",
        photo: "/images/coaches/jess-strickland.jpg",
        hometown: "Gresham, Oregon",
        favoriteTeam: "Portland Timbers",
        favoriteMeal: "Steak",
        license: "USSF D License",
        yearsExperience: "5",
        reason: "I wanted to help my kids' teams in any way that I could.",
        philosophy: "Soccer is life!",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Daniel Sundstrom",
        title: "Coach",
        slug: "daniel-sundstrom",
        photo: "/images/coaches/daniel-sundstrom.jpg",
        hometown: "Oregon City",
        favoriteTeam: "Timbers",
        favoriteMeal: "Pizza",
        license: "Grassroots (Intro, 11v11 Online)",
        yearsExperience: "6",
        reason: "I’ve been helping the same girls for 5 years.",
        philosophy: "Holistic and long term development approach.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Ryan Tomac",
        title: "Coach",
        slug: "ryan-tomac",
        photo: "/images/coaches/ryan-tomac.jpg",
        hometown: "Portland, OR",
        favoriteTeam: "Portland Thorns",
        favoriteMeal: "Screen Door fried chicken",
        license: "USSF D License",
        yearsExperience: "10",
        reason: "Because this is my community, and I am happy to support the growth of young people here through a game I love. I’ve stayed because of the club’s genuine commitment to player development.",
        philosophy: "To develop young players who can think for themselves on the field, learn to compete and play for their teammates, grow in confidence as both players and young people, and develop a lasting love for the game along the way.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "PJ Waskiewicz",
        title: "Coach",
        slug: "pj-waskiewicz",
        photo: "/images/coaches/pj-waskiewicz.jpg",
        hometown: "Bear Creek, Pennsylvania",
        favoriteTeam: "Manchester United",
        favoriteMeal: "Steamed Crab Legs",
        license: "Grassroots (Intro)",
        yearsExperience: "3",
        reason: "My daughter's new team under Coach Borschel had no assistant coach. I wanted to give him the most bandwidth possible to focus on the girls during training and games, so I offered to be an assistant to help wherever I can.",
        philosophy: "I believe that encouraging players when they try something new, even if it's not correct or done well, is a way to build confidence. And with confidence, they will have the courage to try new things that are hard and uncomfortable. I want them to grow as individuals first, let them learn who they are. Then anything is possible.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Nina Wegner",
        title: "Coach",
        slug: "nina-wegner",
        photo: "/images/coaches/placeholder.jpg",
        hometown: "Beavercreek Oregon",
        favoriteTeam: "Timbers",
        favoriteMeal: "Spaghetti",
        license: "Grassroots (Intro)",
        yearsExperience: "15+",
        reason: "My kids started playing for CUSC.",
        philosophy: "I am a coach because I am passionate about my work. I teach my athletes to be responsible, respectful, and to have a good work ethic. I teach them how to work with a team, how to communicate, and how to grow to their best ability.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Wesley Wegner",
        title: "Coach",
        slug: "wesley-wegner",
        photo: "/images/coaches/wesley-wegner.jpg",
        hometown: "Beavercreek",
        favoriteTeam: "Portland Timbers",
        favoriteMeal: "Fajitas",
        license: "Grassroots (Intro)",
        yearsExperience: "15+",
        reason: "Recommendation from family regarding the community, technical skill of coaches and organization of the culub",
        philosophy: "Every player should have the opportunity to reach their highest potential as a player, teammate, friend, family member, and member of the community. Providing support, opportunity and technical guidance to achieve this possibility is my focus.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Cassidy Young",
        title: "Coach",
        slug: "cassidy-young",
        photo: "/images/coaches/cassidy-young.jpg",
        hometown: "Portland, Oregon",
        favoriteTeam: "Arsenal",
        favoriteMeal: "Steak and mashed potatoes",
        license: "USSF D License",
        yearsExperience: "6",
        reason: "I coach for CUSC because the club shaped my development as a player and I want to give back the skills, values, and opportunities I received to our community. I believe in CUSC’s philosophy of teamwork, development, and sportsmanship, and I’m committed to modeling those principles on and off the field. As a female coach, I strive to be a visible leader and mentor for our young girls, showing them what’s possible and helping them grow in confidence, skill, and love for the game.",
        philosophy: "As a coach, I focus on a player-centered approach to development while focusing on the technical, tactical, physical and mental of players both on and off the field. I strive to create a safe, positive, and fun environment where mistakes are learning opportunities and long-term growth is prioritized over short-term results. My sessions use age-appropriate, game-realistic exercises and small-sided games to foster decision-making and player autonomy, and provide players with consistent, and constructive feedback to support continual progress. I emphasize teamwork, leadership, resilience, healthy habits, and clear communication with players and parents, all grounded in respect, accountability, and a love of the game.",
        email: null,
        hidden: false,
        teams: [],
        isDefault: false
    },
    {
        name: "Alex Chen",
        title: "Youth Development Coach",
        slug: "alex-chen",
        photo: "/images/coaches/placeholder.jpg", // Using a generic placeholder
        hometown: "Happy Valley, OR",
        favoriteTeam: "Liverpool FC",
        favoriteMeal: "Sushi",
        license: "USSF D License",
        yearsExperience: null,
        reason: "I grew up playing in the area and wanted to give back to the next generation of players at a club that values community.",
        philosophy: "Focus on the fundamentals. A strong command of the basics gives players the confidence to express themselves on the field.",
        email: null,
        hidden: true, // This coach will not appear in the dropdown
        teams: ["2016 Boys Red", "2016 Boys White"],
        isDefault: false
    }
];